### ISSUE TITLE
生成了一个空白文档

### ISSUE THREAD

**Issue by qtvbwfn** [apiggs/apiggs-maven-plugin#1]
![image](https://user-images.githubusercontent.com/5848026/47541273-43ca5000-d90b-11e8-9ad2-2cee62185206.png)

![image](https://user-images.githubusercontent.com/5848026/47541306-6197b500-d90b-11e8-9ed1-c4b250ba2251.png)

**Comment by ayz6uem** [comment]
你的project是有子项目的么？

**Comment by ayz6uem** [comment]
maven插件默认只能扫描当前项目中的controllers
或者使用source指定源码全路径
```
<configuration>
  <source>xx</source>
</configuration>
```

**Comment by qtvbwfn** [comment]
![image](https://user-images.githubusercontent.com/5848026/47542383-ba694c80-d90f-11e8-8858-3deccde450f6.png)

本身是一个子项目，但是所有的配置都在子项目里边，见截图

**Comment by ayz6uem** [comment]
应该是扫描源码时出现了问题，可以先试一下通过配置指定源码
后边我会将插件完善

**Comment by ayz6uem** [comment]
@qtvbwfn 解决了吗？
